# This file is just a test example. Please see documentation for better options explanation.
compression_level: 9
skip_compression:
  - "*.7z"

exclude:
  - ".vscode"
  - ".git"
  - "*.exe"

max_full_count: 4
max_diff_count: 2
max_diff_size_percent: 50
max_total_diff_size_percent: 80
cleanup: after
