---
lsi: false
safe: true
incremental: false
title: mtsaver documentation
description: 7zip-based differential backups management utility

remote_theme: pages-themes/architect@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
...
