---
lsi: false
safe: true
incremental: false
title: mtsaver docs
description: simple differential backups management command-line utility (7zip based)

remote_theme: pages-themes/architect@v0.2.0
plugins:
  - jekyll-remote-theme
...
